---
- name: Update the apt index
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install packages for apt add repository
  become: true
  ansible.builtin.apt:
    name: '{{ packagesdep }}'
    state: present
  vars:
    packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gpg
      - gnupg2
      - curl
      - python3-pip
      - htop
      - vim
      - locales-all
