stages:
  - quality
  - containerize
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
  policy: pull-push
  paths:
    - node_modules
    - .pnpm-store

variables:
  ANSIBLE_FORCE_COLOR: 'true'
  ANSIBLE_CONFIG: $CI_PROJECT_DIR/ansible/ansible.cfg

.node: &node
  image: docker.io/node:21.7.3-alpine3.18@sha256:2d77508808463f835e81f103aa6693ce929cce73d234e9fd4dae9e062af08748
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm i --frozen-lockfile

.ansible: &ansible
  image:
    name: ghcr.io/hm-edu/ansible-ci:v1.8.15@sha256:2ea58c4e205fed6f793462aff25870e8977935b92cf060ca1d0d706d8e480673
    entrypoint: ['']
  cache: []

next-build:
  <<: *node
  stage: quality
  script:
    - pnpm build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

next-lint:
  <<: *node
  stage: quality
  script:
    - pnpm lint
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

next-prettier:
  <<: *node
  stage: quality
  script:
    - pnpm prettier:check
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

next-test:
  <<: *node
  stage: quality
  script:
    - pnpm test:unit
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

next-test-e2e:
  stage: quality
  image: mcr.microsoft.com/playwright:v1.43.1-jammy-amd64@sha256:1df0e51224b46d872a4185e6c8d6f4b40c22eada49316bb3fd2ade18d0af9536
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm i --frozen-lockfile
    - pnpm build
  script:
    - NEXTAUTH_URL=http://localhost:3000
      SHIBBOLETH_OIDC_ISSUER_URL=https://sso.hm.edu
      SHIBBOLETH_OIDC_SCOPE=openid
      NEXTAUTH_SECRET=topsecret
      SHIBBOLETH_OIDC_CLIENT_ID='$OIDC_CLIENT_ID'
      SHIBBOLETH_OIDC_CLIENT_SECRET='$OIDC_CLIENT_SECRET'
      pnpm test:e2e
  artifacts:
    when: always
    paths:
      - test-results/**/*.webm
      - test-results/**/*.png
      - test-results/**/*.zip
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

ansible-syntax:
  <<: *ansible
  stage: quality
  script:
    - ansible-playbook --syntax-check ansible/playbooks/*
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

ansible-lint:
  <<: *ansible
  stage: quality
  script:
    - ansible-lint -p ansible/playbooks ansible/roles
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

containerize:
  stage: containerize
  cache: []
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug@sha256:7b3699e9e105521075812cd3f3f4c62c913cb5cd113c929975502022df3bcf60
    entrypoint: ['']
  parallel:
    matrix:
      - IMAGE: [shibboleth-oidc-poc, reverse-proxy]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile ./containerize/${IMAGE}/Dockerfile-amd64
      --destination $CI_REGISTRY_IMAGE/${IMAGE}:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
  <<: *ansible
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ansible-playbook
      --extra-vars="
      commit_short_sha='$CI_COMMIT_SHORT_SHA'
      gitlab_registry='$CI_REGISTRY'
      gitlab_registry_user='$CI_REGISTRY_USER'
      gitlab_registry_password='$CI_JOB_TOKEN'
      acme_eab_kid='$ACME_EAB_KID'
      acme_eab_hmac_encoded='$ACME_EAB_HMAC_ENCODED'
      shibboleth_oidc_poc_nextauth_debug='$NEXTAUTH_DEBUG'
      shibboleth_oidc_poc_nextauth_secret='$NEXTAUTH_SECRET'
      shibboleth_oidc_poc_client_id='$OIDC_CLIENT_ID'
      shibboleth_oidc_poc_client_secret='$OIDC_CLIENT_SECRET'"
      ansible/playbooks/shibboleth-oidc-poc.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
