stages:
  - build
  - quality
  - containerize

.node: &node
  image: docker.io/node:21.7.1-alpine3.18@sha256:e020db2afd747842ce18ceb760a225ad2bb3e03586edde241085fcac65135d0f
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

build:
  <<: *node
  stage: build
  script:
    - pnpm i --frozen-lockfile
  only:
    - main
    - merge_requests

lint:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm lint
  only:
    - main
    - merge_requests

prettier:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm prettier:check
  only:
    - main
    - merge_requests

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug@sha256:7b3699e9e105521075812cd3f3f4c62c913cb5cd113c929975502022df3bcf60
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile-amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
