stages:
  - build
  - quality
  - containerize

.node: &node
  image: docker.io/node:21.0.0-alpine3.18@sha256:8e45a0b0116f3789221c27e3011aa68516da2210bdaf76d11719a914e14a3411
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

build:
  <<: *node
  stage: build
  script:
    - pnpm i --frozen-lockfile
  only:
    - main
    - merge_requests

lint:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm lint
  only:
    - main
    - merge_requests

prettier:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm prettier:check
  only:
    - main
    - merge_requests

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.17.0-debug@sha256:97c78eedb0560b8fcf64900abdb810f84f9882d033421f4aee1e6559f42b7e87
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
