stages:
  - build
  - quality
  - containerize

.node: &node
  image: docker.io/node:21.5.0-alpine3.18@sha256:5de525db380e21fd0619b0ca1cff958737a0dc151b3736dc53b7d10e62948d15
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

build:
  <<: *node
  stage: build
  script:
    - pnpm i --frozen-lockfile
  only:
    - main
    - merge_requests

lint:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm lint
  only:
    - main
    - merge_requests

prettier:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm prettier:check
  only:
    - main
    - merge_requests

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug@sha256:899886a2db1c127ff1565d5c7b1e574af1810bbdad048e9850e4f40b5848d79c
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
