stages:
  - build
  - quality
  - containerize

.node: &node
  image: docker.io/node:21.4.0-alpine3.18@sha256:b6d402d8378a31a836e8d93d6f9205a3003b45a85dee2dfad31a934bb9a8002f
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

build:
  <<: *node
  stage: build
  script:
    - pnpm i --frozen-lockfile
  only:
    - main
    - merge_requests

lint:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm lint
  only:
    - main
    - merge_requests

prettier:
  <<: *node
  stage: quality
  script:
    - pnpm i --frozen-lockfile
    - pnpm prettier:check
  only:
    - main
    - merge_requests

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.19.1-debug@sha256:f60ace157b4ce9dd2275981838351da93ed7e0c1eca0efbd82512ee57e95cb59
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
