services:
  reverse-proxy:
    image: gitlab.lrz.de:5005/hm-seclab/projects/shibboleth-sp-oidc/reverse-proxy:{{ commit_short_sha }}
    restart: always
    container_name: reverse-proxy
    hostname: reverse-proxy
    networks:
      - shibboleth-oidc-poc-net
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - ACME_EAB_KID={{ acme_eab_kid }}
      - ACME_EAB_HMAC_ENCODED={{ acme_eab_hmac_encoded }}
      - DOMAIN={{ shibboleth_oidc_poc_domain }}

  shibboleth-oidc-poc:
    image: gitlab.lrz.de:5005/hm-seclab/projects/shibboleth-sp-oidc/shibboleth-oidc-poc:{{ commit_short_sha }}
    restart: always
    container_name: shibboleth-oidc-poc
    hostname: shibboleth-oidc-poc
    networks:
      - shibboleth-oidc-poc-net
    environment:
      - NEXTAUTH_URL=https://{{ shibboleth_oidc_poc_domain }}
      - NEXTAUTH_SECRET={{ shibboleth_oidc_poc_nextauth_secret }}
      - SHIBBOLETH_OIDC_ISSUER_URL={{ shibboleth_oidc_poc_issuer_url }}
      - SHIBBOLETH_OIDC_SCOPE={{ shibboleth_oidc_poc_scope }}
      - SHIBBOLETH_OIDC_CLIENT_ID={{ shibboleth_oidc_poc_client_id }}
      - SHIBBOLETH_OIDC_CLIENT_SECRET={{ shibboleth_oidc_poc_client_secret }}

networks:
  shibboleth-oidc-poc-net:
    name: shibboleth-oidc-poc-network
    driver: bridge

volumes:
  caddy-data:
    name: caddy-data
    driver: local
  caddy-config:
    name: caddy-config
    driver: local
