name: Ensure necessary software quality gates

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build application
        run: pnpm build
  quality-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Check with linter
        run: pnpm lint
  quality-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Check with prettier
        run: pnpm prettier:check
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run unit tests
        run: pnpm test:unit
  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.1-jammy-amd64@sha256:1df0e51224b46d872a4185e6c8d6f4b40c22eada49316bb3fd2ade18d0af9536
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build application
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          NEXTAUTH_URL: http://localhost:3000
          SHIBBOLETH_OIDC_ISSUER_URL: https://sso.hm.edu
          SHIBBOLETH_OIDC_SCOPE: openid
          NEXTAUTH_SECRET: topsecret
          SHIBBOLETH_OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
          SHIBBOLETH_OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
